[supabase]
supabase_url = "https://xefwjtmmuyumtonlxnhv.supabase.co"
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlZndqdG1tdXl1bXRvbmx4bmh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMzc5NjgsImV4cCI6MjA1ODcxMzk2OH0.Vey-e7ShqyqT6FGI-eeED07mgNqnvUL7fO2ZF4wuhYw"

[gemini]
api_key = "AIzaSyAuRaOHe9jmLd74ILvwh59MoC2-mYjdkII"
